Repository Ileriayo/markdown-badges, pull requests merged in 2021-11, with the labels that each got.

#269 Add a new group ORM and add new badge to this named Sequelize
  README.md
Labels: new-badge, new-section

#270 Add Prisma badge
  README.md
Labels: new-badge

#275 Remove Previous Shortcut Option ORM
  README.md
Labels: typo-fix

#278 Fixed #277
  README.md
  _config.yml
Labels: enhancement

#282 Fixed issues from 281 and added languages to close 276
  README.md
Labels: new-badge, new-section
