Repository Ileriayo/markdown-badges, pull requests merged in 2021-10, with the labels that each got.

#229 Fortran Badge
  README.md
Labels: new-badge

#236 Adding Expo Badge
  README.md
Labels: new-badge

#237 Add new badge for socials: TeamSpeack
  README.md
Labels: new-badge

#234 Adding Confluence and XING Badge
  README.md
Labels: new-badge, hacktoberfest-accepted

#245 Added Badges - Haskell , Meetup , GeeksforGeeks
  README.md
Labels: new-badge, hacktoberfest-accepted

#246 Add Spyder IDE
  README.md
Labels: new-badge

#244 Added Badges of Codechef and Leetcode.
  README.md
Labels: new-badge, hacktoberfest-event

#243 Added ( p5.js and Asperite ) badges & back to top button under each category
  README.md
Labels: enhancement, new-badge, hacktoberfest-accepted
