Repository Ileriayo/markdown-badges, pull requests merged in 2021-08, with the labels that each got.

#176 Added new badges and "search engine" section
  README.md
Labels: new-badge, new-section

#181 fix: remove unnecessary characters in raspberry pi badge (Issue#180)
  README.md
Labels: typo-fix

#183 fix: change Postman icon color to white (Issue#182)
  README.md
Labels: typo-fix

#185 Fixed Node.js badge color
  README.md
Labels: typo-fix

#186 "Cryptocurrency" section and some badges added
  README.md
Labels: new-badge, new-section

#187 [Swagger] icon added
  README.md
Labels: new-badge

#188 Added "Android Studio" in "IDEs/Editors/"
  README.md
Labels: new-badge

#189 Add Manjaro and Linux Mint badge
  README.md
Labels: new-badge

#192 Put index list in alphabetical order
  README.md
Labels: enhancement

#190 fixed color & added more in Cryptocurrency
  README.md
Labels: new-badge, typo-fix

#191 color scheme were fixed and added cryptocurrency
  README.md
Labels: new-badge, typo-fix

#193 Added Alpine Linux badge.
  README.md
Labels: new-badge

#195 fixed badge color
  README.md
Labels: typo-fix

#196 Add the Gulp badge
  README.md
Labels: new-badge

#199 Add the Yarn badge and Fix Visual Studio Code and Visual Studio badges
  README.md
Labels: new-badge, typo-fix

#198 added paytm and phonepe in funding
  README.md
Labels: new-badge

#202 added new badges in different sections!
  README.md
Labels: new-badge

#212 Added Singlestore and removed redundant Oracle badge
  README.md
Labels: new-badge

#214 Added Thymeleaf badge.
  README.md
Labels: new-badge

#215 Go: Add alternative name Golang
  README.md
Labels: enhancement

#216 Add Neovim and Emacs to IDEs/Editors and Plotly to ML/DL
  README.md
Labels: new-badge
