Repository Ileriayo/markdown-badges, pull requests merged in 2022-09, with the labels that each got.

#427 Fix: Vultr link text to Vultr
  README.md
Labels: typo-fix

#426 Edit Kotlin color to suitable one
  README.md
Labels: typo-fix

#403 fix: add missing exclamation mark to 'Quasar' and 'LineageOS' Markdown
  README.md
Labels: typo-fix

#397 feat: adding ReScript lang badge
  README.md
Labels: new-badge

#290 Added TeamCity & ChipperCI
  README.md
Labels: new-badge, changes-requested

#424 Added Prefect and Matplotlib badges
  README.md
Labels: new-badge
