Repository Ileriayo/markdown-badges, pull requests merged in 2023-05, with the labels that each got.

#553 Added ChatGPT Icon to the Artificial Intelligence and Bots Area
  README.md
Labels: new-badge

#554 Added - Espressif - Badges
  README.md
Labels: changes-requested

#549 bootstrap colour changed to bootstrap 5 theme colour
  README.md
Labels: enhancement
